### ISSUE TITLE
There are some data formatting errors in python (TypeError: expected string or bytes-like object, got 'Formatter')

### ISSUE THREAD

**Issue by Z-lemon1** [Waste-Wood/ReCo#1]
Could you provide the required versions of python, transformers, and torch

**Comment by Waste-Wood** [comment]
Thanks for following our work.
Maybe this problem doesn't come from the versions of python, transformers, or torch. It would be better to locate the error if you provide the full error message. However, you can also try the following versions of python, transformers and torch:
python >= 3.6
torch >= 1.2
transformers >= 4.0

**Comment by Z-lemon1** [comment]
Thanks for your answer.
The following figure shows the specific information reported in the error
![微信截图_20240424145905](https://github.com/Waste-Wood/ReCo/assets/145957484/d443d97d-624c-4287-9f17-a5b07819f683)

**Comment by Waste-Wood** [comment]
It seems the issue comes from the logging package, just comment line 22 in `./utils/tool.py`, then add an additional code like:
```python
formatter = logging.Formatter('%(asctime)s %(levelname)-8s: %(message)s')
# logging.basicConfig(format=formatter, level=logging.INFO)
logging.basicConfig(format='%(asctime)s %(levelname)-8s: %(message)s', level=logging.INFO)
```
